# Generated by Django 4.2 on 2023-04-14 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinica",
            fields=[
                (
                    "cod_cli",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("nome_cli", models.CharField(max_length=40)),
                ("endereco", models.CharField(blank=True, max_length=40, null=True)),
                ("telefone", models.CharField(blank=True, max_length=16, null=True)),
                ("email", models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                (
                    "cod_espec",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("nome_espec", models.CharField(max_length=25)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "cod_med",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("nome_med", models.CharField(max_length=40)),
                ("genero", models.CharField(blank=True, max_length=40, null=True)),
                ("telefone", models.CharField(blank=True, max_length=16, null=True)),
                ("email", models.CharField(max_length=40, unique=True)),
                (
                    "cod_espec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicasmedicas.especialidade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClinicaMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_ingresso", models.DateField()),
                (
                    "carga_horaria_semanal",
                    models.DecimalField(decimal_places=1, default=20.0, max_digits=3),
                ),
                (
                    "cod_cli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicasmedicas.clinica",
                    ),
                ),
                (
                    "cod_med",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicasmedicas.medico",
                    ),
                ),
            ],
            options={"unique_together": {("cod_cli", "cod_med")},},
        ),
    ]
