# Generated by Django 4.2 on 2023-04-14 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinica",
            fields=[
                (
                    "cod_cli",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnderecoClinica",
            fields=[
                (
                    "cod_end_clinica",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("rua_cli", models.CharField(max_length=20)),
                ("bairro_cli", models.CharField(max_length=20)),
                ("cep_cli", models.CharField(max_length=9)),
                ("numero_end_cli", models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                (
                    "cod_espec",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("nome_espec", models.CharField(max_length=25)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "cod_med",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("genero", models.CharField(max_length=40)),
                (
                    "cod_espec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicasmedicas.especialidade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailClinica",
            fields=[
                (
                    "cod_cli",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clinicasmedicas.clinica",
                    ),
                ),
                ("email_cli", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="EmailMedico",
            fields=[
                (
                    "cod_med",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clinicasmedicas.medico",
                    ),
                ),
                ("email_med", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="NomeClinica",
            fields=[
                (
                    "cod_cli",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clinicasmedicas.clinica",
                    ),
                ),
                ("nome_cli", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="NomeMedico",
            fields=[
                (
                    "cod_med",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clinicasmedicas.medico",
                    ),
                ),
                ("nome_med", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="TelefoneClinica",
            fields=[
                (
                    "cod_cli",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clinicasmedicas.clinica",
                    ),
                ),
                ("telefone_cli", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="TelefoneMedico",
            fields=[
                (
                    "cod_med",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clinicasmedicas.medico",
                    ),
                ),
                ("telefone_med", models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name="clinica",
            name="cod_end_clinica",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clinicasmedicas.enderecoclinica",
            ),
        ),
        migrations.CreateModel(
            name="ClinicaMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_ingresso", models.DateField()),
                (
                    "carga_horaria_semanal",
                    models.DecimalField(decimal_places=1, default=20.0, max_digits=3),
                ),
                (
                    "cod_cli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicasmedicas.clinica",
                    ),
                ),
                (
                    "cod_med",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicasmedicas.medico",
                    ),
                ),
            ],
            options={"unique_together": {("cod_cli", "cod_med")},},
        ),
    ]
