# Generated by Django 4.2 on 2023-04-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinica",
            fields=[
                (
                    "CodCli",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("NomeCli", models.CharField(max_length=40)),
                ("Endereco", models.CharField(blank=True, max_length=40, null=True)),
                ("Telefone", models.CharField(blank=True, max_length=16, null=True)),
                ("Email", models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                (
                    "CodEspec",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("NomeEspec", models.CharField(max_length=25)),
                ("Descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "CodMed",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("NomeMed", models.CharField(max_length=40)),
                ("Genero", models.CharField(blank=True, max_length=40, null=True)),
                ("Telefone", models.CharField(blank=True, max_length=16, null=True)),
                ("Email", models.CharField(max_length=40, unique=True)),
                (
                    "CodEspec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicasmedicas.especialidade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClinicaMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DataIngresso", models.DateField()),
                (
                    "CargaHorariaSemanal",
                    models.DecimalField(decimal_places=1, default=20.0, max_digits=3),
                ),
                (
                    "CodCli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicasmedicas.clinica",
                    ),
                ),
                (
                    "CodMed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicasmedicas.medico",
                    ),
                ),
            ],
            options={"unique_together": {("CodCli", "CodMed")},},
        ),
    ]
